

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.10"

